"""Generated indexes: memory/index-<area>.md per area, and a generated block inside memory/MEMORY.md.

The block lists every active note while the whole of MEMORY.md stays within budget, so an agent finds a note
in the file Claude Code already loads. Once the list would not fit, the block lists the area indexes instead.
Everything in MEMORY.md outside the block is left as written.
"""
from pathlib import Path

from . import config, frontmatter, gitlog, state

START = config.BLOCK_START
END = config.BLOCK_END
MAX_LINES = 150
MAX_BYTES = 17000
GENERATED_MARK = "Generated by receipts-wiki from note frontmatter."


def area_index_for(home, cwd):
    """The memory index for a working directory: the nearest folder, walking up from cwd, whose name matches
    an existing memory/index-<name>.md. The user's home folder and the filesystem root are never matched."""
    if not cwd:
        return None
    try:
        path = Path(cwd).expanduser().resolve()
    except (OSError, RuntimeError):
        return None
    home = Path(home)
    if path == home or home in path.parents:
        return None
    stop = {Path.home().resolve(), Path(path.anchor)}
    for folder in [path, *path.parents]:
        if folder in stop:
            break
        index = home / "memory" / f"index-{gitlog.slug(folder.name)}.md"
        if index.is_file():
            return index
    return None


def is_index_file(rel):
    name = Path(rel).name
    return rel.startswith("memory/") and name.startswith("index-") and name.endswith(".md")


def is_generated_index(home, rel):
    """An index file that receipts-wiki wrote, recognised by its generated mark.

    Index files written by hand before receipts-wiki was installed carry no mark and are never regenerated.
    A deleted file is judged by its committed version.
    """
    if not is_index_file(rel):
        return False
    try:
        head = (Path(home) / rel).read_text(encoding="utf-8", errors="replace")[:400]
    except OSError:
        head = (gitlog.head_content(home, rel) or "")[:400]
    return GENERATED_MARK in head


def is_generated(home, rel):
    return rel == "memory/MEMORY.md" or is_generated_index(home, rel)


def is_note(rel):
    return rel.startswith("memory/") and rel != "memory/MEMORY.md" and not is_index_file(rel)


def notes(home, include=None):
    """Notes on disk; with include, only those whose relative path is in include."""
    found = []
    for path in sorted((Path(home) / "memory").glob("*.md")):
        rel = f"memory/{path.name}"
        if path.name == "MEMORY.md" or path.name.startswith("index-"):
            continue
        if include is not None and rel not in include:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm, _ = frontmatter.split(text)
        found.append({
            "file": path.name,
            "name": str(frontmatter.get(fm, "name") or path.stem),
            "description": " ".join(str(frontmatter.get(fm, "description") or "").split()),
            "area": gitlog.slug(frontmatter.get(fm, "metadata.area", "area") or "general"),
            "status": str(frontmatter.get(fm, "status", "metadata.status") or "active"),
            "type": str(frontmatter.get(fm, "metadata.type", "type") or ""),
            "frontmatter": fm,
            "text": text,
        })
    return found


def note_line(item):
    description = f": {item['description']}" if item["description"] else ""
    return f"- [{item['name']}]({item['file']}){description}"


def render_area(area, items):
    lines = [f"# {area} index", "", f"{GENERATED_MARK} Edit the notes, not this file.", ""]
    if not items:
        lines.append("No active notes.")
    lines.extend(note_line(item) for item in sorted(items, key=lambda n: n["name"].lower()))
    return "\n".join(lines) + "\n"


def render_cursors(cursors):
    """Cursor notes get their own section at the top of the block; empty when there are none."""
    if not cursors:
        return []
    lines = ["## Where things stand", ""]
    lines.extend(note_line(item) for item in sorted(cursors, key=lambda n: n["name"].lower()))
    lines.append("")
    return lines


def render_notes(groups):
    lines = ["## Notes", ""]
    if not groups:
        lines.append("No notes yet.")
    for area in sorted(groups):
        lines.append(f"{area}:")
        lines.extend(note_line(item) for item in sorted(groups[area], key=lambda n: n["name"].lower()))
    return lines


def render_areas(counts):
    lines = ["## Areas", ""]
    if not counts:
        lines.append("No notes yet.")
    for area in sorted(counts):
        lines.append(f"- [{area}](index-{area}.md): {counts[area]} notes")
    return lines


def _block(cursors, body_lines):
    return "\n".join([START, *render_cursors(cursors), *body_lines, END])


def within_budget(text):
    return text.count("\n") <= MAX_LINES and len(text.encode("utf-8")) <= MAX_BYTES


def audit(home):
    """Read-only findings about the index FILES themselves, for lint. Writes nothing.

    `build` reports some of this too, but only to whoever calls it, and the turn path has no business
    printing during a turn. These are standing conditions, so lint is where they belong.
    """
    memory = Path(home) / "memory"
    found = []
    counts = {}
    for item in notes(home):
        if item["status"] != "retired" and item["type"] != "cursor":
            counts[item["area"]] = counts.get(item["area"], 0) + 1

    # Which indexes are actually auto-loaded, from the working directories sessions have recorded.
    # Guessing from the area name would flag sub-indexes that no directory matches.
    loaded = {}
    for data in state.all_sessions(home):
        index = area_index_for(home, data.get("cwd"))
        if index:
            loaded.setdefault(index.name[len("index-"):-len(".md")], data["cwd"])

    for path in sorted(memory.glob("index-*.md")):
        rel = f"memory/{path.name}"
        try:
            raw = path.read_bytes()
        except OSError:
            continue
        area = path.name[len("index-"):-len(".md")]
        # The session-start hook loads at most AREA_INDEX_CHARS of the index for the working directory
        # and drops the rest, saying so only in the text it hands the agent. Nothing else notices.
        # Only the indexes sessions have actually loaded are reported: a sub-index nothing auto-loads may
        # be as long as the structural budget allows, and warning about it would be noise.
        if len(raw) > config.AREA_INDEX_CHARS and area in loaded:
            found.append(
                f"{rel} is {len(raw)} bytes and sessions working in {loaded[area]} load it, so only its first "
                f"{config.AREA_INDEX_CHARS} characters reach them and the rest is silently dropped. Split the "
                f"area (set metadata.area on the notes that belong elsewhere) or shorten the lines.")
        if not is_generated_index(home, rel) and counts.get(area):
            found.append(
                f"{rel} is written by hand, so receipts-wiki never regenerates it: the {counts[area]} active "
                f"notes in area '{area}' stay listed only as long as you edit this file yourself. A renamed or "
                f"added note does not appear on its own.")
    return found


def _splice(current, block):
    if START in current and END in current:
        return current.split(START, 1)[0] + block + current.split(END, 1)[1]
    return current.rstrip("\n") + "\n\n" + block + "\n"


def build(home, include=None):
    """Rewrite index files whose content changed. Returns (changed paths relative to home, budget warnings)."""
    memory = Path(home) / "memory"
    groups = {}
    cursors = []
    for item in notes(home, include):
        if item["status"] == "retired":
            continue
        if item["type"] == "cursor":
            cursors.append(item)
        else:
            groups.setdefault(item["area"], []).append(item)
    existing = {path.name[len("index-"):-len(".md")] for path in memory.glob("index-*.md")
                if is_generated_index(home, f"memory/{path.name}")}

    changed, warnings = [], []
    for area in sorted(set(groups) | existing):
        path = memory / f"index-{area}.md"
        if path.exists() and not is_generated_index(home, f"memory/{path.name}"):
            warnings.append(f"memory/{path.name} was written by hand, so receipts-wiki does not regenerate it; "
                            f"the {len(groups.get(area, []))} notes with area '{area}' are listed there only as "
                            f"long as someone keeps editing it")
            continue
        text = render_area(area, groups.get(area, []))
        if _write_if_changed(path, text):
            changed.append(f"memory/{path.name}")
        if not within_budget(text):
            warnings.append(f"memory/{path.name} is {text.count(chr(10))} lines / {len(text.encode('utf-8'))} bytes, over the {MAX_LINES}-line / {MAX_BYTES}-byte budget; split the area or move detail into notes")

    root = memory / "MEMORY.md"
    current = root.read_text(encoding="utf-8", errors="replace") if root.exists() else "# Memory map\n"
    updated = _splice(current, _block(cursors, render_notes(groups)))
    if not within_budget(updated):
        updated = _splice(current, _block(cursors, render_areas({area: len(items) for area, items in groups.items()})))
    if _write_if_changed(root, updated):
        changed.append("memory/MEMORY.md")
    return changed, warnings


def _write_if_changed(path, text):
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")
    return True
