"""Generated indexes: memory/index-<area>.md per area, and a generated block inside memory/MEMORY.md.

The block lists every active note while the whole of MEMORY.md stays within budget, so an agent finds a note
in the file Claude Code already loads. Once the list would not fit, the block lists the area indexes instead.
Everything in MEMORY.md outside the block is left as written.
"""
from pathlib import Path

from . import config, frontmatter, gitlog

START = config.BLOCK_START
END = config.BLOCK_END
MAX_LINES = 150
MAX_BYTES = 17000


def is_index_file(rel):
    name = Path(rel).name
    return rel.startswith("memory/") and name.startswith("index-") and name.endswith(".md")


def is_generated(rel):
    return rel == "memory/MEMORY.md" or is_index_file(rel)


def notes(home, include=None):
    """Notes on disk; with include, only those whose relative path is in include."""
    found = []
    for path in sorted((Path(home) / "memory").glob("*.md")):
        rel = f"memory/{path.name}"
        if path.name == "MEMORY.md" or path.name.startswith("index-"):
            continue
        if include is not None and rel not in include:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm, _ = frontmatter.split(text)
        found.append({
            "file": path.name,
            "name": str(frontmatter.get(fm, "name") or path.stem),
            "description": " ".join(str(frontmatter.get(fm, "description") or "").split()),
            "area": gitlog.slug(frontmatter.get(fm, "metadata.area", "area") or "general"),
            "status": str(frontmatter.get(fm, "status", "metadata.status") or "active"),
            "type": str(frontmatter.get(fm, "metadata.type", "type") or ""),
            "frontmatter": fm,
            "text": text,
        })
    return found


def note_line(item):
    description = f": {item['description']}" if item["description"] else ""
    return f"- [{item['name']}]({item['file']}){description}"


def render_area(area, items):
    lines = [f"# {area} index", "", "Generated by receipts-wiki from note frontmatter. Edit the notes, not this file.", ""]
    if not items:
        lines.append("No active notes.")
    lines.extend(note_line(item) for item in sorted(items, key=lambda n: n["name"].lower()))
    return "\n".join(lines) + "\n"


def render_notes(groups):
    lines = [START, "## Notes", ""]
    if not groups:
        lines.append("No notes yet.")
    for area in sorted(groups):
        lines.append(f"{area}:")
        lines.extend(note_line(item) for item in sorted(groups[area], key=lambda n: n["name"].lower()))
    lines.append(END)
    return "\n".join(lines)


def render_areas(counts):
    lines = [START, "## Areas", ""]
    if not counts:
        lines.append("No notes yet.")
    for area in sorted(counts):
        lines.append(f"- [{area}](index-{area}.md): {counts[area]} notes")
    lines.append(END)
    return "\n".join(lines)


def within_budget(text):
    return text.count("\n") <= MAX_LINES and len(text.encode("utf-8")) <= MAX_BYTES


def _splice(current, block):
    if START in current and END in current:
        return current.split(START, 1)[0] + block + current.split(END, 1)[1]
    return current.rstrip("\n") + "\n\n" + block + "\n"


def build(home, include=None):
    """Rewrite index files whose content changed. Returns (changed paths relative to home, budget warnings)."""
    memory = Path(home) / "memory"
    groups = {}
    for item in notes(home, include):
        if item["status"] != "retired":
            groups.setdefault(item["area"], []).append(item)
    existing = {path.name[len("index-"):-len(".md")] for path in memory.glob("index-*.md")}

    changed, warnings = [], []
    for area in sorted(set(groups) | existing):
        text = render_area(area, groups.get(area, []))
        path = memory / f"index-{area}.md"
        if _write_if_changed(path, text):
            changed.append(f"memory/{path.name}")
        if not within_budget(text):
            warnings.append(f"memory/{path.name} is {text.count(chr(10))} lines / {len(text.encode('utf-8'))} bytes, over the {MAX_LINES}-line / {MAX_BYTES}-byte budget; split the area or move detail into notes")

    root = memory / "MEMORY.md"
    current = root.read_text(encoding="utf-8", errors="replace") if root.exists() else "# Memory map\n"
    updated = _splice(current, render_notes(groups))
    if not within_budget(updated):
        updated = _splice(current, render_areas({area: len(items) for area, items in groups.items()}))
    if _write_if_changed(root, updated):
        changed.append("memory/MEMORY.md")
    return changed, warnings


def _write_if_changed(path, text):
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")
    return True
